server.port=8080
spring.application.name=API-GATEWAY

# =========================================================
# EUREKA
# =========================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# =========================================================
# GATEWAY
# =========================================================
spring.cloud.gateway.discovery.locator.enabled=false

# =========================================================
# MANAGEMENT
# =========================================================
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

# =========================================================
# SWAGGER UI
# =========================================================
springdoc.swagger-ui.path=/swagger-ui.html

# =========================================================
# SWAGGER - ACCOUNT
# =========================================================
spring.cloud.gateway.routes[0].id=account-service-swagger
spring.cloud.gateway.routes[0].uri=lb://account-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/account-service/v3/api-docs
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[0].name=Account Service
springdoc.swagger-ui.urls[0].url=/account-service/v3/api-docs


# =========================================================
# SWAGGER - PAYMENT PROCESSOR
# =========================================================
spring.cloud.gateway.routes[1].id=payment-processor-service-swagger
spring.cloud.gateway.routes[1].uri=lb://payment-processor-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/payment-processor-service/v3/api-docs
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[1].name=Payment Processor Service
springdoc.swagger-ui.urls[1].url=/payment-processor-service/v3/api-docs


# =========================================================
# SWAGGER - LEDGER
# =========================================================
spring.cloud.gateway.routes[2].id=ledger-service-swagger
spring.cloud.gateway.routes[2].uri=lb://ledger-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/ledger-service/v3/api-docs
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[2].name=Ledger Service
springdoc.swagger-ui.urls[2].url=/ledger-service/v3/api-docs


# =========================================================
# SWAGGER - ORDER
# =========================================================
spring.cloud.gateway.routes[3].id=order-service-swagger
spring.cloud.gateway.routes[3].uri=lb://order-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/order-service/v3/api-docs
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/order-service/v3/api-docs


# =========================================================
# SWAGGER - PAYMENT
# =========================================================
spring.cloud.gateway.routes[4].id=payment-service-swagger
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/payment-service/v3/api-docs
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[4].name=Payment Service
springdoc.swagger-ui.urls[4].url=/payment-service/v3/api-docs


# =========================================================
# SWAGGER - TRANSACTION
# =========================================================
spring.cloud.gateway.routes[5].id=transaction-service-swagger
spring.cloud.gateway.routes[5].uri=lb://transaction-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/transaction-service/v3/api-docs
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[5].name=Transaction Service
springdoc.swagger-ui.urls[5].url=/transaction-service/v3/api-docs


# =========================================================
# SWAGGER - SETTLEMENT
# =========================================================
spring.cloud.gateway.routes[6].id=settlement-service-swagger
spring.cloud.gateway.routes[6].uri=lb://settlement-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/settlement-service/v3/api-docs
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[6].name=Settlement Service
springdoc.swagger-ui.urls[6].url=/settlement-service/v3/api-docs


# =========================================================
# SWAGGER - FRAUD
# =========================================================
spring.cloud.gateway.routes[7].id=fraud-service-swagger
spring.cloud.gateway.routes[7].uri=lb://fraud-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/fraud-service/v3/api-docs
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[7].name=Fraud Service
springdoc.swagger-ui.urls[7].url=/fraud-service/v3/api-docs


# =========================================================
# SWAGGER - NOTIFICATION
# =========================================================
spring.cloud.gateway.routes[8].id=notification-service-swagger
spring.cloud.gateway.routes[8].uri=lb://notification-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/notification-service/v3/api-docs
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[8].name=Notification Service
springdoc.swagger-ui.urls[8].url=/notification-service/v3/api-docs


# =========================================================
# SWAGGER - AUDIT
# =========================================================
spring.cloud.gateway.routes[9].id=audit-service-swagger
spring.cloud.gateway.routes[9].uri=lb://audit-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/audit-service/v3/api-docs
spring.cloud.gateway.routes[9].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[9].name=Audit Service
springdoc.swagger-ui.urls[9].url=/audit-service/v3/api-docs


# =========================================================
# SWAGGER - MERCHANT
# =========================================================
spring.cloud.gateway.routes[10].id=merchant-service-swagger
spring.cloud.gateway.routes[10].uri=lb://SECURE-PAY-MERCHANT-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/secure-pay-merchant-service/v3/api-docs
spring.cloud.gateway.routes[10].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[10].name=Merchant Service
springdoc.swagger-ui.urls[10].url=/secure-pay-merchant-service/v3/api-docs


# =========================================================
# SWAGGER - AUTH
# =========================================================
spring.cloud.gateway.routes[11].id=auth-service-swagger
spring.cloud.gateway.routes[11].uri=lb://auth-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/auth-service/v3/api-docs
spring.cloud.gateway.routes[11].filters[0]=StripPrefix=1

springdoc.swagger-ui.urls[11].name=Auth Service
springdoc.swagger-ui.urls[11].url=/auth-service/v3/api-docs