# Server
server.port=8090

# Application
spring.application.name=settlement-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/settlement_db
spring.datasource.username=postgres
spring.datasource.password=user@123

# JPA
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/