# Server
server.port=8761

spring.application.name=EUREKA-SERVER

# Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Management Endpoints
management.endpoints.web.exposure.include=*