# Server
server.port=8085

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Kafka
kafka.bootstrap-server=localhost:9092